# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='django', max_length=50),
            preserve_default=False,
        ),
    ]
